spring:
  application:
    name: skyblock-flipper-backend
  datasource:
    url: jdbc:h2:mem:skyblock
    username: test
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

config:
  hypixel:
    api-url: "https://api.hypixel.net/v2"